-- Create teams table
create table public.teams (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  constraint teams_pkey primary key (id)
) tablespace pg_default;

-- Add column to users
alter table public.users 
add column team_id bigint;

-- Add foreign key constraint
alter table public.users
add constraint users_team_id_fkey
foreign key (team_id) references teams (id)
on update cascade on delete set null;
